name: telegram
on: [push, create, fork, issue_comment, issues, pull_request_review, pull_request_review_comment]
jobs:
  build:
    runs-on: ubuntu-latest
    name: telegram notification
    if: github.repository_owner == 'moshebe'
    steps:
      - uses: actions/checkout@master
      - name: send telegram notification to Gebug tracking group
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}